
local M = {}

local color_utils = require("mirec_color_utils")

local colorscheme = {
-- general
	{"Conceal", {ctermfg=141}},
	{"Cursor", {ctermfg=196, ctermbg=192, cterm={bold=true, nocombine=true}}},
	{"DiffText", {ctermfg=231, ctermbg=32, cterm={bold=true}}},
	{"ErrorMsg", {ctermbg=231, ctermbg=196}},
	{"IncSearch", {ctermfg=231, ctermbg=163, cterm={bold=true}}},
	{"ModeMsg", {ctermfg=205, cterm={bold=true}}},
	{"NonText", {ctermfg=33}},
	{"Normal", {ctermfg=252, ctermbg=16}},
	{"PmenuSbar", {ctermfg=248, ctermbg=237}},
	{"StatusLine", {ctermfg=252, ctermbg=233, cterm={bold=true}}},
	{"StatusLineNC", {ctermfg=252, ctermbg=16}},
	{"TabLineFill", {ctermbg=16}},
	{"TabLineSel", {ctermfg=16, ctermbg=156}},
	{"TermCursor", {cterm={reverse=true}}},
	{"WildMenu", {ctermfg=231, ctermbg=163, cterm={bold=true}}},
	{"WinBar", {ctermfg=231, cterm={bold=true}}},
	{"Whitespace", {ctermfg=242}},

	{"VertSplit", {link="Normal"}},
	{"WinSeparator", {link="VertSplit"}},
	{"WinBarNC", {link="WinBar"}},
	{"EndOfBuffer", {link="NonText"}},
	{"LineNrAbove", {link="LineNr"}},
	{"LineNrBelow", {link="LineNr"}},
	{"QuickFixLine", {link="Search"}},
	{"CursorLineSign", {link="SignColumn"}},
	{"CursorLineFold", {link="FoldColumn"}},
	{"CurSearch", {link="Search"}},
	{"PmenuKind", {link="Pmenu"}},
	{"PmenuKindSel", {link="PmenuSel"}},
	{"PmenuExtra", {link="Pmenu"}},
	{"PmenuExtraSel", {link="PmenuSel"}},
	{"Substitute", {link="Search"}},
	{"MsgSeparator", {link="StatusLine"}},
	{"NormalFloat", {link="Pmenu"}},
	{"FloatBorder", {link="WinSeparator"}},
	{"FloatTitle", {link="Title"}},
	{"FloatFooter", {link="Title"}},


	{"FloatShadow", {}},
	{"FloatShadowThrough", {}},
	{"RedrawDebugNormal", {}},
	{"RedrawDebugClear", {}},
	{"RedrawDebugComposed", {}},
	{"RedrawDebugRecompose", {}},
	{"Error", {ctermbg=231, ctermbg=196}},
	{"Todo", {ctermfg=231, cterm={bold=true}}},


	{"Character", {link="Constant"}},
	{"Boolean", {link="Title"}},
	{"Function", {link="Identifier"}},
	{"Conditional", {link="Statement"}},
	{"Repeat", {link="Statement"}},
	{"Label", {link="Statement"}},
	{"Operator", {link="Statement"}},
	{"Keyword", {link="Statement"}},
	{"Exception", {link="Statement"}},
	{"Include", {link="PreProc"}},
	{"Define", {link="PreProc"}},
	{"Macro", {link="PreProc"}},
	{"PreCondit", {link="PreProc"}},
	{"StorageClass", {link="Type"}},
	{"Structure", {link="Type"}},
	{"Tag", {link="Special"}},
	{"SpecialChar", {link="Special"}},
	{"Delimiter", {link="Special"}},
	{"SpecialComment", {link="Special"}},
	{"Debug", {link="Special"}},


	{"DiagnosticError", {}},
	{"DiagnosticWarn", {}},
	{"DiagnosticInfo", {}},
	{"DiagnosticHint", {}},
	{"DiagnosticOk", {}},
	{"DiagnosticDeprecated", {}},


	{"DiagnosticVirtualTextError", {link="DiagnosticError"}},
	{"DiagnosticVirtualTextWarn", {link="DiagnosticWarn"}},
	{"DiagnosticVirtualTextInfo", {link="DiagnosticInfo"}},
	{"DiagnosticVirtualTextHint", {link="DiagnosticHint"}},
	{"DiagnosticVirtualTextOk", {link="DiagnosticOk"}},
	{"DiagnosticFloatingError", {link="DiagnosticError"}},
	{"DiagnosticFloatingWarn", {link="DiagnosticWarn"}},
	{"DiagnosticFloatingInfo", {link="DiagnosticInfo"}},
	{"DiagnosticFloatingHint", {link="DiagnosticHint"}},
	{"DiagnosticFloatingOk", {link="DiagnosticOk"}},
	{"DiagnosticSignError", {link="DiagnosticError"}},
	{"DiagnosticSignWarn", {link="DiagnosticWarn"}},
	{"DiagnosticSignInfo", {link="DiagnosticInfo"}},
	{"DiagnosticSignHint", {link="DiagnosticHint"}},
	{"DiagnosticSignOk", {link="DiagnosticOk"}},


-- highlighting

	{"ColorColumn", {ctermbg=233}},
	{"CursorColumn", {ctermbg=232}},
	{"CursorLine", {ctermbg=233}},
	{"CursorLineNr", {ctermfg=255, ctermbg=125, cterm={bold=true, nocombine=true}}},
	{"DiffAdd", {ctermbg=22}},
	{"DiffChange", {ctermbg=24}},
	{"DiffDelete", {ctermbg=88}},
	{"Directory", {ctermfg=141}},
	{"FoldColumn", {ctermfg=244, ctermbg=233}},
	{"Folded", {ctermfg=244}},
	{"LineNr", {ctermfg=244, ctermbg=234}},
	{"MatchParen", {ctermfg=255, ctermbg=125, cterm={bold=true, nocombine=true}}},
	{"MoreMsg", {ctermfg=205, cterm={bold=true}}},
	{"Pmenu", {ctermfg=252, ctermbg=235}},
	{"PmenuSel", {ctermfg=16, ctermbg=156}},
	{"PmenuThumb", {ctermfg=248, ctermbg=156}},
	{"Question", {ctermfg=231, cterm={bold=true}}},
	{"Search", {ctermfg=227, ctermbg=233, cterm={bold=true, reverse=true}}},
	{"SignColumn", {ctermfg=244, ctermbg=233}},
	{"SpecialKey", {ctermfg=242}},
	{"SpellBad", {ctermfg=210, ctermbg=233, undercurl=true, cterm={underline=true}}},
	{"SpellCap", {ctermfg=117, undercurl=true, cterm={underline=true}}},
	{"SpellLocal", {ctermfg=117, undercurl=true, cterm={underline=true}}},
	{"SpellRare", {ctermfg=117, undercurl=true, cterm={underline=true}}},
	{"TabLine", {ctermbg=235}},
	{"Title", {ctermfg=231, cterm={bold=true}}},
	{"Visual", {ctermfg=231, ctermbg=163, cterm={bold=true}}},
	{"WarningMsg", {ctermfg=221, cterm={bold=true}}},
	{"Comment", {ctermfg=242}},
	{"Constant", {ctermfg=205, cterm={bold=true}}},
	{"Special", {ctermfg=205, cterm={bold=true}}},
	{"Identifier", {ctermfg=147}},
	{"Statement", {ctermfg=227, cterm={bold=true}}},
	{"PreProc", {ctermfg=47}},
	{"String", {ctermfg=210}},
	{"Type", {ctermfg=153}},
	{"Typedef", {ctermfg=153, cterm={bold=true}}},
	{"Number", {ctermfg=111}},
	{"Underlined", {ctermfg=75, cterm={underline=true}}},
	{"Ignore", {ctermfg=244}},
	{"Float", {ctermfg=219}},
	{"Operator", {ctermfg=153, cterm={bold=true}}},


	--{"Boolean", {ctermfg=7, cterm={bold=true}}},
	--{"Character", {ctermfg=217, cterm={bold=true}}},
	--{"ColorColumn", {ctermbg=234}},
	--{"Comment", {ctermfg=8}},
	--{"Conditional", {ctermfg=228, cterm={bold=true}}},
	--{"Cursor", {ctermfg=0, ctermbg=145}},
	--{"CursorColumn", {ctermbg=232}},
	--{"CursorLine", {ctermbg=232, cterm={underline=true}}},
	--{"Delimiter", {ctermfg=158}},
	--{"Directory", {ctermfg=147}},
	--{"FoldColumn", {ctermfg=192, ctermbg=235}},
	--{"Folded", {ctermfg=192, ctermbg=233}},
	--{"Exception", {ctermfg=228, cterm={bold=true}}},
	--{"PreProc", {ctermfg=156}},
	--{"Identifier", {ctermfg=111}},
	--{"IncSearch", {ctermfg=231, ctermbg=18, cterm={bold=true}}},
	--{"Label", {ctermfg=228}},
	--{"LineNr", {ctermfg=243, ctermbg=235}},
	--{"MatchParen", {ctermfg=192, ctermbg=233, cterm={bold=true, reverse=true}}},
	--{"ModeMsg", {ctermfg=181, cterm={bold=true}}},
	--{"MoreMsg", {ctermfg=231, cterm={bold=true}}},
	--{"NonText", {ctermfg=104}},
	--{"Normal", {ctermfg=252, ctermbg=233}},
	--{"Operator", {ctermfg=158}},
	--{"Pmenu", {ctermfg=231, ctermbg=240}},
	--{"PmenuSel", {ctermfg=0, ctermbg=156}},
	--{"Question", {ctermfg=231, cterm={bold=true}}},
	--{"Repeat", {ctermfg=228, cterm={bold=true}}},
	--{"Search", {ctermfg=227, ctermbg=233, cterm={bold=true, reverse=true}}},
	--{"Special", {ctermfg=217, cterm={bold=true}}},
	--{"SpecialKey", {ctermfg=243}},
	--{"Statement", {ctermfg=228}},
	--{"StatusLine", {cterm={bold=true}, ctermbg=0, ctermfg=2}},
	--{"StatusLineNC", {ctermfg=234, ctermbg=252}},
	--{"String", {ctermfg=204}},
	--{"Title", {ctermfg=231, cterm={bold=true}}},
	--{"Type", {ctermfg=121}},
	--{"VertSplit", {ctermfg=234, ctermbg=252}},
	--{"Visual", {ctermfg=236, ctermbg=210, cterm={reverse=true}}},
	--{"VisualNOS", {ctermfg=234, ctermbg=210, cterm={bold=true, underline=true}}},
	--{"WarningMsg", {ctermfg=224, ctermbg=234, cterm={bold=true}}},
	--{"WildMenu", {ctermfg=0, ctermbg=181}},

	--{"CallClass", {ctermfg=122}},
	--{"CallStaticClass", {ctermfg=231, cterm={bold=true}}},
	--{"CallFunction", {ctermfg=129}},
	--{"CallPrivateFunction", {ctermfg=130}},

	--{"CallFunction", {ctermfg=111}},

	--{"doxygenBrief", {ctermfg=249, cterm={bold=true}}},
	--{"doxygenSpecialOnelineDesc", {ctermfg=123}},

	{"@variable", {}},
	{"@attribute", {link="Attribute"}},
	{"@property", {link="Attribute"}},
	{"@field", {link="Attribute"}},
	{"@variable.python", {}},
	{"@variable.builtin.python", {link="Self"}},
	{"@variable.class.python", {link="Title"}},
	{"@constant.builtin.python", {link="Boolean"}},
	{"@constant.python", {link="Title"}},
	{"@exception.builtin.python", {link="Structure"}},
	{"@function.builtin.python", {link="Function"}},
	{"@function.call.python", {}},
	{"@function.class_construct.python", {link="CallClass"}},
	{"@function.call_private.python", {link="CallPrivateFunction"}},
	{"@definition.import.python", {}},
	{"@definition.superclasses.python", {link="Title"}},
	{"@definition.decorator.python", {link="Function"}},
	{"@definition.classname.python", {link="DefineClass"}},
	{"@attribute.python", {}},
	{"@field.python", {link="Attribute"}},
	{"@property.python", {}},
	{"@parameter.python", {}},
	{"@tag.vue", {link="Statement"}},
	{"@tag.attribute.vue", {link="Type"}},
	{"@method.vue", {link="Type"}},
	{"@punction.special.vue", {link="Type"}},
	{"@none.vue", {link="Type"}},
}


M.setup = function(config)
	color_utils.setup_colorscheme(colorscheme, 'mirec2', 'dark')
end

return M
